# User Settings | Edit there as per required

title: accent
url: "http://thehvardhan.me"
baseurl: ""

# This will show up at the top of index page
site_heading: >
    Harsh Vardhan <span class="faded">'s blog</span>

email: harshvd95@gmail.com
author: hvardhan
# This description will show up in google search results
# (for index page) etc.
description: >
    The chosen one!

# This will what will show against &copy; in the footer
copyright: accent
# Toggle your short bio, which will displayed on your index page
# Just toggle it and run jekyll again to see
intro: false         # Tip: Remove the span from site_heading if intro is set to true
# This will be displayed in your intro
short_bio: >
    Welcome! This is <span>accent</span>, a mobile friendly theme for Jekyll. The main feature of this
    theme is that you can change the accent color. Refer the
    <a class="underline different-highlight" href="#">
        Documentation
    </a>
    to know how.

permalink: /:title.html

# Comments are powered by disqus
comments: true

# keep about_stub roughly 12 words long for best results
# This will show up at the bottom of each post
# Note that about_footer should be true if you want
# to see author information at the bottom of each post
about_stub: >
    I am Harsh Vardhan and I blog about new technologies and conferences around the world.

about_footer: true

twitter_username: royalharsh95
github_username: royalharsh
facebook_id: royalharsh95

favicon: true
favicon_location: "images/favicon.ico"

profile_picture: images/profile.jpg
paginate: 5
paginate_path: "/page/:num"
tracking_id: UA-77550279-1 # GA Tracking ID

# Social Stuff | open graph and twitter cards
og_image: "images/profile.jpg" # This will show in facebook thumbnails
twitter_image: "images/profile.jpg" # This will show in twitter cards

####################################
####################################
####################################
### Build Settings | Don't Touch ###
####################################
####################################
####################################

markdown: kramdown

gems:
    - jekyll-paginate
    - jemoji

sass:
    style: compressed
    sass_dir: _sass

# Scopes
defaults:
    -
        scope:
            path:   ""
            type:   "pages"
        values:
            layout: "page"
    -
        scope:
            path:   ""
            type:   "posts"
        values:
            layout: "post"

exclude: [vendor] # For travis ci
